# preload = /home/lucas/Pictures/tianshu-liu.jpg
# wallpaper = ,/home/lucas/Pictures/tianshu-liu.jpg
# splash = false

wallpaper {
    monitor = eDP-1
    path = /home/lucas/Pictures/tianshu-liu.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/lucas/Pictures/tianshu-liu.jpg
    fit_mode = cover
}
